# Generated by Django 3.1.6 on 2022-03-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('lastseen', models.DateTimeField()),
                ('macid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.temperaturehumidity')),
            ],
        ),
    ]
